const COLORS=['#ef9db0','#9bcfa7','#f5ca68','#9bc8ee','#c7b0ea','#f3aa91','#91d1bd','#e7ceb7','#e88f97','#8fc6b0'];
const DB_NAME='ricettario_pwa_db';
const DB_STORE='app';
const DB_KEY='state';
const LEGACY_KEY='ricettario_pwa_v1';
const APP_VERSION='2.0.0';
const DEFAULT_STATE={version:2,cookbooks:[],settings:{displayName:'',theme:'light'}};
let state=structuredCloneSafe(DEFAULT_STATE);
let route={view:'home',cookbookId:null,recipeId:null};
let ingredientDraft=[];
let draftPhoto=null;
let searchMode='all';
let deferredInstallPrompt=null;
let db=null;
let toastTimer=null;

const ICONS={
  back:'<path d="m15 18-6-6 6-6"/>',
  plus:'<path d="M12 5v14M5 12h14"/>',
  books:'<path d="M4 19.5V6.2c0-.7.5-1.2 1.2-1.2H8v14.5H5.2A1.2 1.2 0 0 1 4 18.3"/><path d="M8 5h4v14.5H8M12 6l4-1 3 13.5-4 1z"/>',
  search:'<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>',
  heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8l1.1 1.1L12 21l7.8-7.5 1.1-1.1a5.5 5.5 0 0 0-.1-7.8z"/>',
  gear:'<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-2.8 2.8-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.6v.2h-4V21a1.7 1.7 0 0 0-1-1.6 1.7 1.7 0 0 0-1.9.3l-.1.1L4.2 17l.1-.1a1.7 1.7 0 0 0 .3-1.9A1.7 1.7 0 0 0 3 14H2.8v-4H3a1.7 1.7 0 0 0 1.6-1 1.7 1.7 0 0 0-.3-1.9L4.2 7 7 4.2l.1.1a1.7 1.7 0 0 0 1.9.3 1.7 1.7 0 0 0 1-1.6v-.2h4V3a1.7 1.7 0 0 0 1 1.6 1.7 1.7 0 0 0 1.9-.3l.1-.1L19.8 7l-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.6 1h.2v4H21a1.7 1.7 0 0 0-1.6 1z"/>',
  download:'<path d="M12 3v12"/><path d="m7 10 5 5 5-5"/><path d="M5 21h14"/>',
  share:'<circle cx="18" cy="5" r="2.5"/><circle cx="6" cy="12" r="2.5"/><circle cx="18" cy="19" r="2.5"/><path d="m8.2 10.8 7.6-4.6M8.2 13.2l7.6 4.6"/>',
  edit:'<path d="M12 20h9"/><path d="M16.5 3.5a2.1 2.1 0 0 1 3 3L8 18l-4 1 1-4z"/>',
  trash:'<path d="M3 6h18M8 6V4h8v2M19 6l-1 15H6L5 6M10 11v6M14 11v6"/>',
  clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
  oven:'<rect x="4" y="3" width="16" height="18" rx="2"/><path d="M4 8h16M8 5.5h.01M12 5.5h.01M8 12h8v5H8z"/>',
  temp:'<path d="M14 14.8V5a2 2 0 1 0-4 0v9.8a4 4 0 1 0 4 0z"/><path d="M12 9v7"/>',
  camera:'<path d="M5 7h3l1.5-2h5L16 7h3a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2z"/><circle cx="12" cy="13" r="4"/>',
  user:'<circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/>',
  backup:'<path d="M12 3v11"/><path d="m8 7 4-4 4 4"/><path d="M5 13v7h14v-7"/>',
  restore:'<path d="M3 12a9 9 0 1 0 3-6.7L3 8"/><path d="M3 3v5h5"/>',
  info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7h.01"/>',
  filter:'<path d="M4 6h16M7 12h10M10 18h4"/>'
};
function icon(name,cls=''){return `<span class="${cls}"><svg viewBox="0 0 24 24" aria-hidden="true">${ICONS[name]||''}</svg></span>`}
function structuredCloneSafe(v){return typeof structuredClone==='function'?structuredClone(v):JSON.parse(JSON.stringify(v))}
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function normalizeState(raw){
  const s=raw&&typeof raw==='object'?raw:structuredCloneSafe(DEFAULT_STATE);
  s.version=2;s.settings={...DEFAULT_STATE.settings,...(s.settings||{})};s.cookbooks=Array.isArray(s.cookbooks)?s.cookbooks:[];
  s.cookbooks=s.cookbooks.map(b=>({id:b.id||uid(),name:b.name||'Ricettario',color:b.color||COLORS[0],createdAt:b.createdAt||new Date().toISOString(),recipes:Array.isArray(b.recipes)?b.recipes.map(r=>({id:r.id||uid(),name:r.name||'Ricetta',ingredients:Array.isArray(r.ingredients)?r.ingredients:[],procedure:r.procedure||'',photo:r.photo||null,cooking:{method:r.cooking?.method||'',temperature:r.cooking?.temperature||'',time:r.cooking?.time||''},favorite:!!r.favorite,createdAt:r.createdAt||new Date().toISOString(),updatedAt:r.updatedAt||r.createdAt||new Date().toISOString()})):[]}));
  return s;
}
function openDatabase(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>{const d=req.result;if(!d.objectStoreNames.contains(DB_STORE))d.createObjectStore(DB_STORE)};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
function dbRead(){return new Promise((resolve,reject)=>{const tx=db.transaction(DB_STORE,'readonly');const req=tx.objectStore(DB_STORE).get(DB_KEY);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
function dbWrite(value){return new Promise((resolve,reject)=>{const tx=db.transaction(DB_STORE,'readwrite');tx.objectStore(DB_STORE).put(value,DB_KEY);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
async function loadState(){
  try{db=await openDatabase();const saved=await dbRead();if(saved)return normalizeState(saved);const legacy=localStorage.getItem(LEGACY_KEY);if(legacy){const migrated=normalizeState(JSON.parse(legacy));await dbWrite(migrated);return migrated}return normalizeState(DEFAULT_STATE)}catch(e){console.warn('IndexedDB non disponibile, uso localStorage',e);try{return normalizeState(JSON.parse(localStorage.getItem(LEGACY_KEY)))}catch{return normalizeState(DEFAULT_STATE)}}
}
async function saveState(){try{if(db)await dbWrite(state);else localStorage.setItem(LEGACY_KEY,JSON.stringify(state))}catch(e){console.error(e);showToast('Impossibile salvare i dati') }}
function getCookbook(id=route.cookbookId){return state.cookbooks.find(b=>b.id===id)}
function getRecipe(bookId=route.cookbookId,recipeId=route.recipeId){return getCookbook(bookId)?.recipes.find(r=>r.id===recipeId)}
function allRecipes(){return state.cookbooks.flatMap(b=>(b.recipes||[]).map(r=>({book:b,recipe:r})))}
function go(view,cookbookId=null,recipeId=null){route={view,cookbookId,recipeId};render();window.scrollTo(0,0)}
function bookSymbol(name=''){const n=name.toLowerCase();if(/dolc|tort|dessert|biscott/.test(n))return'🧁';if(/focacc|pane|pizza|lievit/.test(n))return'🥖';if(/primi|pasta|riso/.test(n))return'🍝';if(/second|carne|pesce/.test(n))return'🍽️';if(/contorn|verdure|veget/.test(n))return'🌿';if(/bev|drink/.test(n))return'🥤';if(/colaz/.test(n))return'🥐';return'♡'}
function metaText(r){const parts=[];if(r.cooking?.time)parts.push(`${r.cooking.time} min`);if(r.cooking?.method)parts.push(r.cooking.method);return parts.join(' · ')||`${r.ingredients.length} ingredient${r.ingredients.length===1?'e':'i'}`}
function bottomNav(active){return `<nav class="bottom-nav" aria-label="Navigazione principale">${navButton('home','books','Ricettari',active)}${navButton('search','search','Cerca',active)}${navButton('favorites','heart','Preferiti',active)}${navButton('settings','gear','Impostazioni',active)}</nav>`}
function navButton(view,ico,label,active){return `<button class="nav-item ${active===view?'active':''}" data-nav="${view}">${icon(ico)}<span>${label}</span></button>`}
function showToast(msg){const el=document.querySelector('#toast');if(!el)return;el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2200)}

function render(){
  const app=document.querySelector('#app');let html='';
  if(route.view==='home')html=homeView();
  else if(route.view==='new-cookbook'||route.view==='edit-cookbook')html=cookbookFormView();
  else if(route.view==='cookbook')html=cookbookView();
  else if(route.view==='new-recipe'||route.view==='edit-recipe')html=recipeFormView();
  else if(route.view==='recipe')html=recipeView();
  else if(route.view==='search')html=searchView();
  else if(route.view==='favorites')html=favoritesView();
  else if(route.view==='settings')html=settingsView();
  else html=homeView();
  app.innerHTML=html;bindEvents();
}

function homeView(){const name=state.settings.displayName?.trim();return `<main class="app-shell page-enter"><div class="home-head"><div class="hello"><div class="hello-mark">🍞</div><div><h1>${name?`Ciao, ${esc(name)}!`:'Ciao!'}</h1><p>I tuoi ricettari, sempre con te</p></div></div><button class="circle-btn primary" data-action="new-cookbook" aria-label="Nuovo ricettario">${icon('plus')}</button></div>${state.cookbooks.length?`<section class="book-grid">${state.cookbooks.map(bookCard).join('')}</section>`:`<div class="empty"><span class="emoji">📚</span><h2>Il tuo primo ricettario</h2><p>Crea una raccolta, scegli il colore della copertina e comincia a salvare le tue ricette.</p><button class="primary-btn green" data-action="new-cookbook">Crea ricettario</button></div>`}${bottomNav('home')}</main>`}
function bookCard(b){return `<article class="book-card"><button class="book-cover" style="background:${b.color}" data-open-book="${b.id}" aria-label="Apri ${esc(b.name)}"><span class="book-symbol">${bookSymbol(b.name)}</span><h2>${esc(b.name)}</h2><small>${b.recipes.length} ${b.recipes.length===1?'ricetta':'ricette'}</small></button><button class="book-menu" data-edit-book="${b.id}" aria-label="Modifica ${esc(b.name)}">${icon('edit')}</button></article>`}

function cookbookFormView(){const editing=route.view==='edit-cookbook';const b=editing?getCookbook():null;const color=b?.color||COLORS[0];return `<main class="app-shell no-nav page-enter"><header class="topbar center"><button class="back-btn" data-action="home">${icon('back')}</button><div class="top-title"><h1>${editing?'Modifica ricettario':'Nuovo ricettario'}</h1></div><span></span></header><div class="preview-wrap"><div class="book-preview"><div class="book-cover" id="bookPreview" style="background:${color}"><span class="book-symbol" id="bookPreviewSymbol">${bookSymbol(b?.name||'')}</span><h2 id="bookPreviewName">${esc(b?.name||'Il mio ricettario')}</h2></div></div></div><section class="panel"><div class="form-group"><label>Nome ricettario <span class="required">*</span></label><input id="bookName" value="${esc(b?.name||'')}" placeholder="Es. Dolci" maxlength="50"></div><div class="form-group"><label>Scegli un colore</label><div class="color-row">${COLORS.map(c=>`<button class="color-dot ${c===color?'selected':''}" style="background:${c}" data-color="${c}" aria-label="Scegli colore"></button>`).join('')}</div></div><div class="button-stack"><button class="primary-btn" data-action="save-cookbook">${editing?'Salva modifiche':'Crea ricettario'}</button>${editing?`<button class="danger-btn" data-action="delete-cookbook">Elimina ricettario</button>`:''}</div></section></main>`}

function cookbookView(){const b=getCookbook();if(!b)return homeView();return `<main class="app-shell no-nav page-enter"><section class="cookbook-hero" style="background:${b.color}"><header class="topbar center"><button class="back-btn" data-action="home">${icon('back')}</button><div class="top-title"><h1>${esc(b.name)}</h1><p>${b.recipes.length} ${b.recipes.length===1?'ricetta':'ricette'}</p></div><button class="circle-btn" data-action="edit-current-book" aria-label="Modifica ricettario">${icon('edit')}</button></header><div class="hero-search"><input class="search-input" id="recipeSearch" placeholder="Cerca in ${esc(b.name)}..."><button class="filter-btn" aria-label="Filtro">${icon('filter')}</button></div><div class="book-actions"><button data-action="book-pdf">${icon('download','inline-icon')} PDF ricettario</button><button data-action="share-book">${icon('share','inline-icon')} Condividi PDF</button></div></section><section class="recipe-list" id="recipeList">${renderRecipeList((b.recipes||[]).map(r=>({book:b,recipe:r})))}</section><button class="fab" data-action="new-recipe">${icon('plus')} Aggiungi ricetta</button></main>`}
function renderRecipeList(entries,emptyMessage='Ancora nessuna ricetta'){if(!entries.length)return `<div class="empty"><span class="emoji">🥣</span><h2>${emptyMessage}</h2><p>Le ricette che salvi compariranno qui.</p></div>`;return entries.map(({book,recipe:r})=>`<article class="recipe-item"><div class="recipe-open" data-open-recipe="${r.id}" data-book-id="${book.id}">${r.photo?`<img class="recipe-thumb" src="${r.photo}" alt="">`:`<div class="recipe-thumb recipe-fallback">${bookSymbol(book.name)}</div>`}<div class="recipe-copy"><h3>${esc(r.name)}</h3><p>${route.view==='search'||route.view==='favorites'?`<span class="recipe-book-label">${esc(book.name)}</span> · `:''}${esc(metaText(r))}</p></div></div><button class="heart-btn ${r.favorite?'active':''}" data-favorite-recipe="${r.id}" data-book-id="${book.id}" aria-label="${r.favorite?'Rimuovi dai preferiti':'Aggiungi ai preferiti'}">${icon('heart')}</button></article>`).join('')}

function beginNewRecipe(){ingredientDraft=[];draftPhoto=null;go('new-recipe',route.cookbookId)}
function beginEditRecipe(){const r=getRecipe();if(!r)return;ingredientDraft=[...r.ingredients];draftPhoto=r.photo||null;go('edit-recipe',route.cookbookId,route.recipeId)}
function recipeFormView(){const editing=route.view==='edit-recipe';const r=editing?getRecipe():null;const b=getCookbook();if(!b)return homeView();return `<main class="app-shell no-nav page-enter"><header class="topbar center"><button class="back-btn" data-action="${editing?'recipe':'book'}">${icon('back')}</button><div class="top-title"><h1>${editing?'Modifica ricetta':'Nuova ricetta'}</h1></div><button class="circle-btn primary" data-action="save-recipe" aria-label="Salva">✓</button></header><section class="panel"><div class="form-group"><label>Nome della ricetta <span class="required">*</span></label><input id="recipeName" value="${esc(r?.name||'')}" placeholder="Es. Torta di mele" maxlength="100"></div><div class="form-group"><label>Ingredienti <span class="required">*</span></label><div class="ingredient-add"><input id="ingredientInput" placeholder="Es. 300 g farina"><button class="add-btn" data-action="add-ingredient">＋ Aggiungi</button></div><div class="ingredients-editor" id="ingredientList">${ingredientEditorHtml()}</div></div><div class="form-group"><label>Procedimento <span class="optional">(facoltativo)</span></label><textarea id="procedure" placeholder="Scrivi qui il procedimento...">${esc(r?.procedure||'')}</textarea></div><div class="form-group"><label>Foto <span class="optional">(facoltativa)</span></label><div class="photo-zone" id="photoBox">${photoBoxHtml()}</div><div class="photo-buttons"><button data-action="camera-photo">📷 Scatta foto</button><button data-action="gallery-photo">▣ Scegli dalla galleria</button></div></div><div class="form-group"><label>Cottura <span class="optional">(facoltativa)</span></label><div class="cooking-grid"><select id="method"><option value="">Metodo</option>${['Forno statico','Forno ventilato','Padella','Friggitrice ad aria','Pentola','Vapore','Senza cottura','Altro'].map(x=>`<option ${r?.cooking?.method===x?'selected':''}>${x}</option>`).join('')}</select><div class="input-unit"><input id="temperature" type="number" min="0" max="500" value="${esc(r?.cooking?.temperature||'')}" placeholder="180"><span>°C</span></div><div class="input-unit"><input id="time" type="number" min="0" max="9999" value="${esc(r?.cooking?.time||'')}" placeholder="35"><span>min</span></div></div></div><button class="primary-btn green" data-action="save-recipe">${editing?'Salva modifiche':'Salva ricetta'}</button></section></main>`}
function ingredientEditorHtml(){return ingredientDraft.map((x,i)=>`<div class="ingredient-edit"><button class="remove-ing" data-remove-ing="${i}" aria-label="Rimuovi ingrediente">−</button><input value="${esc(x)}" data-ing-index="${i}"></div>`).join('')}
function photoBoxHtml(){return draftPhoto?`<div class="photo-preview"><img src="${draftPhoto}" alt="Anteprima foto"><button class="remove-photo" data-action="remove-photo" aria-label="Rimuovi foto">×</button></div>`:`<div class="photo-empty"><div><div class="camera-big">📷</div><strong>Aggiungi una foto</strong><div style="font-size:12px;margin-top:4px">Scattala ora oppure sceglila dalla galleria</div></div></div>`}

function recipeView(){const r=getRecipe(),b=getCookbook();if(!r||!b)return cookbookView();const hasPhoto=!!r.photo;return `<main class="app-shell no-nav recipe-page page-enter">${hasPhoto?`<div class="recipe-photo-wrap"><img src="${r.photo}" alt="${esc(r.name)}"><div class="recipe-overlay"><button class="back-btn" data-action="book">${icon('back')}</button><button class="circle-btn" data-action="edit-recipe">${icon('edit')}</button></div></div>`:`<header class="topbar center"><button class="back-btn" data-action="book">${icon('back')}</button><div class="top-title"><h1>Ricetta</h1></div><button class="circle-btn" data-action="edit-recipe">${icon('edit')}</button></header>`}<article class="recipe-sheet ${hasPhoto?'':'no-photo'}"><h1 class="recipe-title">${esc(r.name)}</h1><div class="recipe-meta">${r.cooking?.time?`<span class="meta-chip">${icon('clock')} ${r.cooking.time} min</span>`:''}${r.cooking?.method?`<span class="meta-chip">${icon('oven')} ${esc(r.cooking.method)}</span>`:''}${r.cooking?.temperature?`<span class="meta-chip">${icon('temp')} ${r.cooking.temperature} °C</span>`:''}</div><div class="recipe-toolbar"><button data-action="recipe-pdf">${icon('download')}Scarica PDF</button><button data-action="share-recipe">${icon('share')}Condividi PDF</button><button data-action="toggle-current-favorite" class="${r.favorite?'favorite':''}">${icon('heart')}${r.favorite?'Nei preferiti':'Preferiti'}</button></div><section class="recipe-section"><h2>Ingredienti</h2><ul class="clean-list">${r.ingredients.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>${r.procedure?`<section class="recipe-section"><h2>Procedimento</h2><div class="procedure">${esc(r.procedure)}</div></section>`:''}${r.cooking&&(r.cooking.method||r.cooking.temperature||r.cooking.time)?`<section class="recipe-section"><h2>Cottura</h2><div class="cooking-card">${r.cooking.method?`<div class="cook-stat"><span>Metodo</span>${esc(r.cooking.method)}</div>`:''}${r.cooking.temperature?`<div class="cook-stat"><span>Temperatura</span>${r.cooking.temperature} °C</div>`:''}${r.cooking.time?`<div class="cook-stat"><span>Tempo</span>${r.cooking.time} min</div>`:''}</div></section>`:''}<div class="button-stack" style="margin-top:30px"><button class="secondary-btn" data-action="edit-recipe">${icon('edit','inline-icon')} Modifica ricetta</button><button class="danger-btn" data-action="delete-recipe">Elimina ricetta</button></div></article></main>`}

function searchView(){const entries=allRecipes();return `<main class="app-shell page-enter"><header class="search-header"><h1>Cerca</h1></header><div class="search-wrap" id="globalSearchWrap"><span class="search-ico">${icon('search')}</span><input class="search-input" id="globalSearch" placeholder="Nome o ingrediente" autocomplete="off"><button class="clear-search" data-action="clear-search">×</button></div><div class="segmented"><button class="${searchMode==='all'?'active':''}" data-search-mode="all">Tutte</button><button class="${searchMode==='name'?'active':''}" data-search-mode="name">Ricette</button><button class="${searchMode==='ingredients'?'active':''}" data-search-mode="ingredients">Ingredienti</button></div><div id="searchResults">${searchResultsHtml(entries,'')}</div>${bottomNav('search')}</main>`}
function searchResultsHtml(entries,q){const qq=q.toLowerCase().trim();let filtered=entries;if(qq){filtered=entries.filter(({recipe:r})=>searchMode==='name'?r.name.toLowerCase().includes(qq):searchMode==='ingredients'?r.ingredients.some(i=>i.toLowerCase().includes(qq)):r.name.toLowerCase().includes(qq)||r.ingredients.some(i=>i.toLowerCase().includes(qq)))}return `<div class="result-count">${filtered.length} ${filtered.length===1?'risultato':'risultati'}</div><section class="recipe-list">${renderRecipeList(filtered,'Nessuna ricetta trovata')}</section>`}
function favoritesView(){const fav=allRecipes().filter(x=>x.recipe.favorite);return `<main class="app-shell page-enter"><header class="search-header"><h1>Preferiti</h1></header>${fav.length?`<section class="recipe-list">${renderRecipeList(fav)}</section>`:`<div class="empty"><span class="emoji">♡</span><h2>Nessun preferito</h2><p>Tocca il cuore su una ricetta per ritrovarla rapidamente qui.</p></div>`}${bottomNav('favorites')}</main>`}
function settingsView(){const n=state.settings.displayName||'';return `<main class="app-shell page-enter"><header class="settings-header"><h1>Impostazioni</h1></header><section class="settings-section"><h2>Il mio profilo</h2><div class="settings-card"><div class="setting-row"><div class="setting-icon">${icon('user')}</div><div><strong>Nome</strong><br><small>Usato solo nel saluto della Home</small></div><input id="displayName" maxlength="30" value="${esc(n)}" placeholder="Il tuo nome"></div></div></section><section class="settings-section"><h2>Dati</h2><div class="settings-card"><div class="setting-row"><div class="setting-icon">${icon('backup')}</div><div><strong>Esporta backup</strong><br><small>Salva ricettari, ricette e foto</small></div><button data-action="export-backup">Esporta ›</button></div><div class="setting-row"><div class="setting-icon">${icon('restore')}</div><div><strong>Importa backup</strong><br><small>Ripristina un file JSON</small></div><button data-action="import-backup">Importa ›</button></div></div><p class="settings-note">I dati sono salvati localmente sul dispositivo. Il backup è consigliato prima di cancellare dati del browser o cambiare telefono.</p></section><section class="settings-section"><h2>App</h2><div class="settings-card"><div class="setting-row"><div class="setting-icon">＋</div><div><strong>Installa sul telefono</strong><br><small>Aggiungi l'app alla schermata Home</small></div><button data-action="install-app">Installa ›</button></div><div class="setting-row"><div class="setting-icon">${icon('info')}</div><div><strong>Versione</strong></div><small>${APP_VERSION}</small></div></div></section><section class="settings-section"><button class="danger-btn" data-action="reset-app">Cancella tutti i dati</button></section>${bottomNav('settings')}</main>`}

function bindEvents(){
  document.querySelectorAll('[data-action]').forEach(el=>el.addEventListener('click',handleAction));
  document.querySelectorAll('[data-nav]').forEach(el=>el.addEventListener('click',()=>go(el.dataset.nav)));
  document.querySelectorAll('[data-open-book]').forEach(el=>el.addEventListener('click',()=>go('cookbook',el.dataset.openBook)));
  document.querySelectorAll('[data-edit-book]').forEach(el=>el.addEventListener('click',e=>{e.stopPropagation();go('edit-cookbook',el.dataset.editBook)}));
  document.querySelectorAll('[data-open-recipe]').forEach(el=>el.addEventListener('click',()=>go('recipe',el.dataset.bookId,el.dataset.openRecipe)));
  document.querySelectorAll('[data-favorite-recipe]').forEach(el=>el.addEventListener('click',async e=>{e.stopPropagation();await toggleFavorite(el.dataset.bookId,el.dataset.favoriteRecipe);render()}));
  document.querySelectorAll('[data-color]').forEach(el=>el.addEventListener('click',()=>selectColor(el)));
  document.querySelectorAll('[data-search-mode]').forEach(el=>el.addEventListener('click',()=>{searchMode=el.dataset.searchMode;render();setTimeout(()=>document.querySelector('#globalSearch')?.focus(),20)}));
  document.querySelectorAll('[data-remove-ing]').forEach(btn=>btn.addEventListener('click',()=>{syncIngredientDraft();ingredientDraft.splice(+btn.dataset.removeIng,1);refreshIngredientEditor()}));
  document.querySelectorAll('[data-ing-index]').forEach(inp=>inp.addEventListener('input',syncIngredientDraft));
  const bookName=document.querySelector('#bookName');if(bookName)bookName.addEventListener('input',()=>{const n=bookName.value.trim()||'Il mio ricettario';document.querySelector('#bookPreviewName').textContent=n;document.querySelector('#bookPreviewSymbol').textContent=bookSymbol(n)});
  const recipeSearch=document.querySelector('#recipeSearch');if(recipeSearch)recipeSearch.addEventListener('input',()=>{const b=getCookbook();const q=recipeSearch.value.toLowerCase().trim();const entries=(b.recipes||[]).filter(r=>r.name.toLowerCase().includes(q)||r.ingredients.some(i=>i.toLowerCase().includes(q))).map(r=>({book:b,recipe:r}));document.querySelector('#recipeList').innerHTML=renderRecipeList(entries,'Nessuna ricetta trovata');bindDynamicRecipeEvents()});
  const globalSearch=document.querySelector('#globalSearch');if(globalSearch)globalSearch.addEventListener('input',()=>{const wrap=document.querySelector('#globalSearchWrap');wrap.classList.toggle('has-value',!!globalSearch.value);document.querySelector('#searchResults').innerHTML=searchResultsHtml(allRecipes(),globalSearch.value);bindDynamicRecipeEvents()});
  const dn=document.querySelector('#displayName');if(dn)dn.addEventListener('change',async()=>{state.settings.displayName=dn.value.trim();await saveState();showToast('Nome salvato')});
  document.querySelector('#photoInput').onchange=handlePhotoInput;document.querySelector('#cameraInput').onchange=handlePhotoInput;document.querySelector('#backupInput').onchange=handleBackupImport;
}
function bindDynamicRecipeEvents(){document.querySelectorAll('[data-open-recipe]').forEach(el=>el.addEventListener('click',()=>go('recipe',el.dataset.bookId,el.dataset.openRecipe)));document.querySelectorAll('[data-favorite-recipe]').forEach(el=>el.addEventListener('click',async e=>{e.stopPropagation();await toggleFavorite(el.dataset.bookId,el.dataset.favoriteRecipe);render()}))}
function selectColor(el){document.querySelectorAll('[data-color]').forEach(x=>x.classList.remove('selected'));el.classList.add('selected');const p=document.querySelector('#bookPreview');if(p)p.style.background=el.dataset.color}
async function handleAction(e){
  const a=e.currentTarget.dataset.action;
  if(a==='home')return go('home');if(a==='book')return go('cookbook',route.cookbookId);if(a==='recipe')return go('recipe',route.cookbookId,route.recipeId);
  if(a==='new-cookbook')return go('new-cookbook');if(a==='edit-current-book')return go('edit-cookbook',route.cookbookId);if(a==='save-cookbook')return saveCookbook();if(a==='delete-cookbook')return deleteCookbook();
  if(a==='new-recipe')return beginNewRecipe();if(a==='edit-recipe')return beginEditRecipe();if(a==='add-ingredient')return addIngredient();if(a==='save-recipe')return saveRecipe();if(a==='delete-recipe')return deleteRecipe();
  if(a==='gallery-photo')return document.querySelector('#photoInput').click();if(a==='camera-photo')return document.querySelector('#cameraInput').click();if(a==='remove-photo'){draftPhoto=null;refreshPhotoBox();return}
  if(a==='recipe-pdf')return downloadRecipePdf(getRecipe());if(a==='share-recipe')return shareRecipePdf(getRecipe());if(a==='book-pdf')return downloadCookbookPdf(getCookbook());if(a==='share-book')return shareCookbookPdf(getCookbook());
  if(a==='toggle-current-favorite'){await toggleFavorite(route.cookbookId,route.recipeId);return render()}
  if(a==='clear-search'){const i=document.querySelector('#globalSearch');if(i){i.value='';document.querySelector('#globalSearchWrap').classList.remove('has-value');document.querySelector('#searchResults').innerHTML=searchResultsHtml(allRecipes(),'');bindDynamicRecipeEvents();i.focus()}return}
  if(a==='export-backup')return exportBackup();if(a==='import-backup')return document.querySelector('#backupInput').click();if(a==='reset-app')return resetApp();if(a==='install-app')return installApp();
}
function addIngredient(){const input=document.querySelector('#ingredientInput');const v=input?.value.trim();if(!v)return;syncIngredientDraft();ingredientDraft.push(v);input.value='';refreshIngredientEditor();input.focus()}
function syncIngredientDraft(){document.querySelectorAll('[data-ing-index]').forEach(inp=>ingredientDraft[+inp.dataset.ingIndex]=inp.value.trim())}
function refreshIngredientEditor(){const el=document.querySelector('#ingredientList');if(!el)return;el.innerHTML=ingredientEditorHtml();el.querySelectorAll('[data-remove-ing]').forEach(btn=>btn.addEventListener('click',()=>{syncIngredientDraft();ingredientDraft.splice(+btn.dataset.removeIng,1);refreshIngredientEditor()}));el.querySelectorAll('[data-ing-index]').forEach(inp=>inp.addEventListener('input',syncIngredientDraft))}
function refreshPhotoBox(){const box=document.querySelector('#photoBox');if(box)box.innerHTML=photoBoxHtml();const rm=box?.querySelector('[data-action="remove-photo"]');if(rm)rm.addEventListener('click',()=>{draftPhoto=null;refreshPhotoBox()})}
async function handlePhotoInput(e){const file=e.target.files?.[0];if(!file)return;try{draftPhoto=await resizeImageFile(file);refreshPhotoBox();showToast('Foto aggiunta')}catch{showToast('Impossibile leggere la foto')}e.target.value=''}
function resizeImageFile(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const max=1400;let w=img.width,h=img.height;if(w>max||h>max){const scale=Math.min(max/w,max/h);w=Math.round(w*scale);h=Math.round(h*scale)}const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;canvas.getContext('2d').drawImage(img,0,0,w,h);resolve(canvas.toDataURL('image/jpeg',.78))};img.src=reader.result};reader.readAsDataURL(file)})}

async function saveCookbook(){const input=document.querySelector('#bookName');const name=input.value.trim();if(!name){input.focus();return showToast('Inserisci il nome del ricettario')}const color=document.querySelector('.color-dot.selected')?.dataset.color||COLORS[0];if(route.view==='edit-cookbook'){const b=getCookbook();if(!b)return;b.name=name;b.color=color;await saveState();showToast('Ricettario aggiornato');return go('home')}const b={id:uid(),name,color,createdAt:new Date().toISOString(),recipes:[]};state.cookbooks.push(b);await saveState();showToast('Ricettario creato');go('home')}
async function deleteCookbook(){const b=getCookbook();if(!b)return;if(!confirm(`Eliminare il ricettario “${b.name}” e tutte le sue ricette?`))return;state.cookbooks=state.cookbooks.filter(x=>x.id!==b.id);await saveState();showToast('Ricettario eliminato');go('home')}
async function saveRecipe(){syncIngredientDraft();const pendingInput=document.querySelector('#ingredientInput');const pending=pendingInput?.value.trim();if(pending){ingredientDraft.push(pending);pendingInput.value=''}ingredientDraft=ingredientDraft.map(x=>x.trim()).filter(Boolean);const nameInput=document.querySelector('#recipeName');const name=nameInput.value.trim();if(!name){nameInput.focus();return showToast('Inserisci il nome della ricetta')}if(!ingredientDraft.length){document.querySelector('#ingredientInput')?.focus();return showToast('Inserisci almeno un ingrediente')}const data={name,ingredients:[...ingredientDraft],procedure:document.querySelector('#procedure').value.trim(),photo:draftPhoto,cooking:{method:document.querySelector('#method').value,temperature:document.querySelector('#temperature').value,time:document.querySelector('#time').value},updatedAt:new Date().toISOString()};const b=getCookbook();if(route.view==='edit-recipe'){const r=getRecipe();Object.assign(r,data);await saveState();showToast('Ricetta aggiornata');return go('recipe',b.id,r.id)}const r={id:uid(),favorite:false,createdAt:new Date().toISOString(),...data};b.recipes.unshift(r);await saveState();ingredientDraft=[];draftPhoto=null;showToast('Ricetta salvata');go('recipe',b.id,r.id)}
async function deleteRecipe(){const b=getCookbook(),r=getRecipe();if(!b||!r)return;if(!confirm(`Eliminare “${r.name}”?`))return;b.recipes=b.recipes.filter(x=>x.id!==r.id);await saveState();showToast('Ricetta eliminata');go('cookbook',b.id)}
async function toggleFavorite(bookId,recipeId){const r=getRecipe(bookId,recipeId);if(!r)return;r.favorite=!r.favorite;await saveState();showToast(r.favorite?'Aggiunta ai preferiti':'Rimossa dai preferiti')}

function ensurePdf(){if(!window.jspdf?.jsPDF){showToast('Modulo PDF non disponibile: connettiti a Internet e riapri l’app');return false}return true}
function pdfColor(hex){const h=hex.replace('#','');return [parseInt(h.slice(0,2),16),parseInt(h.slice(2,4),16),parseInt(h.slice(4,6),16)]}
function safeFileName(s){return s.replace(/[\\/:*?"<>|]+/g,'-').trim()||'ricetta'}
function addPdfHeader(doc,title,color='#ef9db0'){const [r,g,b]=pdfColor(color);doc.setFillColor(r,g,b);doc.roundedRect(12,12,186,25,5,5,'F');doc.setTextColor(40,35,32);doc.setFont('helvetica','bold');doc.setFontSize(21);doc.text(title,19,29);doc.setTextColor(40,35,32)}
function addWrapped(doc,text,x,y,width,lineHeight=6){for(const line of doc.splitTextToSize(text,width)){if(y>280){doc.addPage();y=20}doc.text(line,x,y);y+=lineHeight}return y}
function renderRecipePdfPage(doc,r,b,startNew=false){if(startNew)doc.addPage();let y=20;const left=18,width=174;addPdfHeader(doc,r.name,b.color);y=47;if(r.photo){try{doc.addImage(r.photo,'JPEG',left,y,75,55,undefined,'FAST');y+=64}catch{}}const meta=[r.cooking?.method,r.cooking?.temperature?`${r.cooking.temperature} °C`:null,r.cooking?.time?`${r.cooking.time} min`:null].filter(Boolean).join(' · ');if(meta){doc.setFont('helvetica','normal');doc.setFontSize(10);doc.setTextColor(105,95,90);doc.text(meta,left,y);doc.setTextColor(40,35,32);y+=10}doc.setFont('helvetica','bold');doc.setFontSize(15);doc.text('Ingredienti',left,y);y+=8;doc.setFont('helvetica','normal');doc.setFontSize(11);r.ingredients.forEach(i=>{y=addWrapped(doc,`• ${i}`,left,y,width,6)});if(r.procedure){y+=7;if(y>250){doc.addPage();y=20}doc.setFont('helvetica','bold');doc.setFontSize(15);doc.text('Procedimento',left,y);y+=8;doc.setFont('helvetica','normal');doc.setFontSize(11);y=addWrapped(doc,r.procedure,left,y,width,6)}if(r.cooking&&(r.cooking.method||r.cooking.temperature||r.cooking.time)){y+=7;if(y>260){doc.addPage();y=20}doc.setFont('helvetica','bold');doc.setFontSize(15);doc.text('Cottura',left,y);y+=8;doc.setFont('helvetica','normal');doc.setFontSize(11);doc.text(meta,left,y)}return doc}
function buildRecipePdf(r,blob=false){if(!ensurePdf())return null;const {jsPDF}=window.jspdf;const doc=new jsPDF();const b=getCookbook();renderRecipePdfPage(doc,r,b,false);return blob?doc.output('blob'):doc}
function buildCookbookPdf(b,blob=false){if(!ensurePdf())return null;if(!b?.recipes.length){showToast('Questo ricettario è vuoto');return null}const {jsPDF}=window.jspdf;const doc=new jsPDF();const [cr,cg,cb]=pdfColor(b.color);doc.setFillColor(cr,cg,cb);doc.rect(0,0,210,297,'F');doc.setTextColor(45,38,34);doc.setFont('helvetica','bold');doc.setFontSize(32);doc.text(b.name,105,120,{align:'center'});doc.setFont('helvetica','normal');doc.setFontSize(13);doc.text(`${b.recipes.length} ${b.recipes.length===1?'ricetta':'ricette'}`,105,136,{align:'center'});doc.setFont('helvetica','bold');doc.setFontSize(12);doc.text('IL MIO RICETTARIO',105,92,{align:'center'});b.recipes.forEach(r=>renderRecipePdfPage(doc,r,b,true));return blob?doc.output('blob'):doc}
function downloadRecipePdf(r){if(!r)return;const doc=buildRecipePdf(r);if(doc)doc.save(`${safeFileName(r.name)}.pdf`)}
function downloadCookbookPdf(b){if(!b)return;const doc=buildCookbookPdf(b);if(doc)doc.save(`${safeFileName(b.name)}-ricettario.pdf`)}
async function sharePdfBlob(blob,fileName,title,text,fallback){const file=new File([blob],fileName,{type:'application/pdf'});if(navigator.canShare&&navigator.canShare({files:[file]})){try{await navigator.share({title,text,files:[file]});return}catch(e){if(e.name==='AbortError')return}}showToast('Condivisione PDF non supportata: scarico il file');fallback()}
async function shareRecipePdf(r){if(!r)return;const blob=buildRecipePdf(r,true);if(blob)await sharePdfBlob(blob,`${safeFileName(r.name)}.pdf`,r.name,`Ricetta: ${r.name}`,()=>downloadRecipePdf(r))}
async function shareCookbookPdf(b){if(!b)return;const blob=buildCookbookPdf(b,true);if(blob)await sharePdfBlob(blob,`${safeFileName(b.name)}-ricettario.pdf`,b.name,`Ricettario: ${b.name}`,()=>downloadCookbookPdf(b))}

function exportBackup(){const payload=JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2);const blob=new Blob([payload],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`ricettari-backup-${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000);showToast('Backup esportato')}
async function handleBackupImport(e){const file=e.target.files?.[0];if(!file)return;try{const raw=JSON.parse(await file.text());if(!Array.isArray(raw.cookbooks))throw new Error('Formato non valido');if(!confirm('Importando il backup sostituirai i dati attuali. Continuare?'))return;state=normalizeState(raw);await saveState();showToast('Backup importato');go('home')}catch{alert('Il file selezionato non è un backup valido.')}finally{e.target.value=''}}
async function resetApp(){if(!confirm('Vuoi cancellare tutti i ricettari e le ricette salvate su questo dispositivo?'))return;if(!confirm('Conferma definitiva: questa operazione non può essere annullata senza un backup.'))return;state=normalizeState(DEFAULT_STATE);await saveState();showToast('Dati cancellati');go('home')}
async function installApp(){if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;return}alert('Per installare l’app: apri il menu del browser e scegli “Aggiungi a schermata Home” o “Installa app”. Su iPhone usa Condividi → Aggiungi alla schermata Home.')}

window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(console.warn));
async function init(){state=await loadState();render()}
init();
