const SUPABASE_URL='https://yncoztexkiuhusaukjcm.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_MyNvin0G8-glYkWJZPLwUw_BSAoii1a';
const APP_URL='https://grecoofabiana2005-hub.github.io/ricettario/';
const APP_VERSION='4.0.0';
const COLORS=['#ef9db0','#9bcfa7','#f5ca68','#9bc8ee','#c7b0ea','#f3aa91','#91d1bd','#e7ceb7','#e88f97','#8fc6b0'];
const DB_NAME='ricettario_pwa_db',DB_STORE='app',LOCAL_KEY='state',LEGACY_KEY='ricettario_pwa_v1';
const DEFAULT_STATE={version:4,cookbooks:[],settings:{displayName:'',theme:'light'}};

let sb=null,currentUser=null,state=clone(DEFAULT_STATE),deviceLocalState=clone(DEFAULT_STATE),db=null;
let route={view:'auth',cookbookId:null,recipeId:null},ingredientDraft=[],draftPhoto=null,draftPhotoChanged=false,searchMode='all';
let deferredInstallPrompt=null,toastTimer=null,recoveryMode=false,loading=false;

const ICONS={
  back:'<path d="m15 18-6-6 6-6"/>',plus:'<path d="M12 5v14M5 12h14"/>',books:'<path d="M4 19.5V6.2c0-.7.5-1.2 1.2-1.2H8v14.5H5.2A1.2 1.2 0 0 1 4 18.3"/><path d="M8 5h4v14.5H8M12 6l4-1 3 13.5-4 1z"/>',
  search:'<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>',heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8l1.1 1.1L12 21l7.8-7.5 1.1-1.1a5.5 5.5 0 0 0-.1-7.8z"/>',
  gear:'<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-2.8 2.8-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.6v.2h-4V21a1.7 1.7 0 0 0-1-1.6 1.7 1.7 0 0 0-1.9.3l-.1.1L4.2 17l.1-.1a1.7 1.7 0 0 0 .3-1.9A1.7 1.7 0 0 0 3 14H2.8v-4H3a1.7 1.7 0 0 0 1.6-1 1.7 1.7 0 0 0-.3-1.9L4.2 7 7 4.2l.1.1a1.7 1.7 0 0 0 1.9.3 1.7 1.7 0 0 0 1-1.6v-.2h4V3a1.7 1.7 0 0 0 1 1.6 1.7 1.7 0 0 0 1.9-.3l.1-.1L19.8 7l-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.6 1h.2v4H21a1.7 1.7 0 0 0-1.6 1z"/>',
  download:'<path d="M12 3v12"/><path d="m7 10 5 5 5-5"/><path d="M5 21h14"/>',share:'<circle cx="18" cy="5" r="2.5"/><circle cx="6" cy="12" r="2.5"/><circle cx="18" cy="19" r="2.5"/><path d="m8.2 10.8 7.6-4.6M8.2 13.2l7.6 4.6"/>',
  edit:'<path d="M12 20h9"/><path d="M16.5 3.5a2.1 2.1 0 0 1 3 3L8 18l-4 1 1-4z"/>',trash:'<path d="M3 6h18M8 6V4h8v2M19 6l-1 15H6L5 6M10 11v6M14 11v6"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
  oven:'<rect x="4" y="3" width="16" height="18" rx="2"/><path d="M4 8h16M8 5.5h.01M12 5.5h.01M8 12h8v5H8z"/>',temp:'<path d="M14 14.8V5a2 2 0 1 0-4 0v9.8a4 4 0 1 0 4 0z"/><path d="M12 9v7"/>',camera:'<path d="M5 7h3l1.5-2h5L16 7h3a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2z"/><circle cx="12" cy="13" r="4"/>',
  user:'<circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/>',backup:'<path d="M12 3v11"/><path d="m8 7 4-4 4 4"/><path d="M5 13v7h14v-7"/>',restore:'<path d="M3 12a9 9 0 1 0 3-6.7L3 8"/><path d="M3 3v5h5"/>',
  info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7h.01"/>',chef:'<path d="M7 10.5a4 4 0 0 1 1.3-7.8A4.5 4.5 0 0 1 12 1a4.5 4.5 0 0 1 3.7 1.7A4 4 0 0 1 17 10.5V18H7z"/><path d="M7 14h10M9 18v3h6v-3"/>',filter:'<path d="M4 6h16M7 12h10M10 18h4"/>',
  logout:'<path d="M10 17l5-5-5-5M15 12H3"/><path d="M14 3h5a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-5"/>',cloud:'<path d="M17.5 19H7a5 5 0 0 1-.8-9.9A7 7 0 0 1 19.8 11 4 4 0 0 1 17.5 19z"/><path d="m9 14 3-3 3 3M12 11v6"/>'
};
const icon=(name,cls='')=>`<span class="${cls}"><svg viewBox="0 0 24 24" aria-hidden="true">${ICONS[name]||''}</svg></span>`;
const clone=v=>typeof structuredClone==='function'?structuredClone(v):JSON.parse(JSON.stringify(v));
const uid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const safeFileName=s=>(s||'ricetta').replace(/[\\/:*?"<>|]+/g,'-').trim()||'ricetta';
const showToast=msg=>{const el=document.querySelector('#toast');if(!el)return;el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2300)};
const setBusy=(on,msg='Attendi...')=>{loading=on;let el=document.querySelector('#busy');if(on){if(!el){el=document.createElement('div');el.id='busy';el.className='busy-overlay';document.body.appendChild(el)}el.innerHTML=`<div class="busy-card"><span class="spinner"></span><strong>${esc(msg)}</strong></div>`}else el?.remove()};

function normalizeState(raw){
  const s=raw&&typeof raw==='object'?raw:clone(DEFAULT_STATE);s.settings={...DEFAULT_STATE.settings,...(s.settings||{})};s.cookbooks=Array.isArray(s.cookbooks)?s.cookbooks:[];
  s.cookbooks=s.cookbooks.map(b=>({id:b.id||uid(),name:b.name||'Ricettario',color:b.color||COLORS[0],createdAt:b.createdAt||new Date().toISOString(),recipes:Array.isArray(b.recipes)?b.recipes.map(r=>({id:r.id||uid(),name:r.name||r.title||'Ricetta',ingredients:Array.isArray(r.ingredients)?r.ingredients:[],procedure:r.procedure||'',photo:r.photo||null,photoPath:r.photoPath||r.photo_path||null,cooking:{method:r.cooking?.method||r.cooking_method||'',temperature:r.cooking?.temperature||r.cooking_temperature||'',time:r.cooking?.time||r.cooking_time||''},favorite:!!r.favorite,createdAt:r.createdAt||r.created_at||new Date().toISOString(),updatedAt:r.updatedAt||r.updated_at||new Date().toISOString()})):[]}));
  return s;
}
function openDatabase(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>{const d=req.result;if(!d.objectStoreNames.contains(DB_STORE))d.createObjectStore(DB_STORE)};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
function dbReadKey(key){return new Promise((resolve,reject)=>{const req=db.transaction(DB_STORE,'readonly').objectStore(DB_STORE).get(key);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
function dbWriteKey(key,val){return new Promise((resolve,reject)=>{const tx=db.transaction(DB_STORE,'readwrite');tx.objectStore(DB_STORE).put(val,key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
async function loadDeviceLocal(){try{db=await openDatabase();const saved=await dbReadKey(LOCAL_KEY);if(saved)return normalizeState(saved);const legacy=localStorage.getItem(LEGACY_KEY);return legacy?normalizeState(JSON.parse(legacy)):normalizeState(DEFAULT_STATE)}catch{return normalizeState(DEFAULT_STATE)}}
async function cacheCloud(){if(currentUser&&db)try{await dbWriteKey(`cloud:${currentUser.id}`,state)}catch{}}
async function cloudCache(){if(!currentUser||!db)return null;try{return normalizeState(await dbReadKey(`cloud:${currentUser.id}`))}catch{return null}}

function getCookbook(id=route.cookbookId){return state.cookbooks.find(b=>b.id===id)}
function getRecipe(bookId=route.cookbookId,recipeId=route.recipeId){return getCookbook(bookId)?.recipes.find(r=>r.id===recipeId)}
function allRecipes(){return state.cookbooks.flatMap(b=>b.recipes.map(r=>({book:b,recipe:r})))}
function go(view,cookbookId=null,recipeId=null){route={view,cookbookId,recipeId};render();scrollTo(0,0)}
function bookSymbol(name=''){const n=name.toLowerCase();let body='';if(/dolc|tort|dessert|biscott/.test(n))body='<path d="M14 18h20l-2 17H16z"/><path d="M13 18c0-5 4-9 9-9 1 0 2 .2 3 .5C27 6 34 8 34 14c0 1.6-.5 3-1.4 4"/><path d="M19 23l1 8M25 23v8M31 23l-1 8"/>';else if(/focacc|pane|pizza|lievit/.test(n))body='<path d="M10 31c-2-8 2-16 11-19 8-3 16 0 18 7 2 7-4 14-13 16-7 2-13 0-16-4z"/><path d="M18 15l4 5M25 12l4 5M32 13l3 4"/>';else if(/primi|pasta|riso/.test(n))body='<path d="M10 28h28c-2 7-7 10-14 10s-12-3-14-10z"/><path d="M14 25c2-5 5-8 10-8s8 3 10 8M18 21c0-5 3-8 6-10M25 20c1-4 4-6 7-8"/>';else if(/second|carne|pesce/.test(n))body='<path d="M8 29h32M12 29c1-9 6-14 12-14s11 5 12 14M24 15v-4M21 11h6"/>';else if(/contorn|verdure|veget/.test(n))body='<path d="M37 10C24 11 14 18 12 34c12 1 21-7 25-24z"/><path d="M12 34c6-7 12-12 20-17"/>';else body='<path d="M24 37 10 24c-7-7 3-18 10-10l4 4 4-4c7-8 17 3 10 10z"/>';return `<svg viewBox="0 0 48 48" aria-hidden="true">${body}</svg>`}
function metaText(r){const p=[];if(r.cooking?.time)p.push(`${r.cooking.time} min`);if(r.cooking?.method)p.push(r.cooking.method);return p.join(' · ')||`${r.ingredients.length} ingredient${r.ingredients.length===1?'e':'i'}`}
function bottomNav(active){return `<nav class="bottom-nav">${navButton('home','books','Ricettari',active)}${navButton('search','search','Cerca',active)}${navButton('favorites','heart','Preferiti',active)}${navButton('settings','gear','Impostazioni',active)}</nav>`}
function navButton(view,ico,label,active){return `<button class="nav-item ${active===view?'active':''}" data-nav="${view}">${icon(ico)}<span>${label}</span></button>`}

function authView(mode='login',message=''){
  const signup=mode==='signup',forgot=mode==='forgot';
  return `<main class="auth-shell page-enter"><section class="auth-brand"><div class="auth-chef">${icon('chef')}</div><h1>I miei ricettari</h1><p>Le tue ricette, sempre con te.</p></section><section class="auth-card"><h2>${signup?'Crea il tuo profilo':forgot?'Recupera password':'Bentornata'}</h2>${message?`<div class="auth-message">${esc(message)}</div>`:''}${signup?`<label>Nome</label><input id="authName" placeholder="Es. Fabiana" maxlength="40">`:''}<label>Email</label><input id="authEmail" type="email" inputmode="email" autocomplete="email" placeholder="nome@email.it">${!forgot?`<label>Password</label><input id="authPassword" type="password" autocomplete="${signup?'new-password':'current-password'}" placeholder="Almeno 6 caratteri">`:''}<button class="primary-btn green" data-action="${signup?'signup':forgot?'send-reset':'login'}">${signup?'Registrati':forgot?'Invia link':'Accedi'}</button>${!signup&&!forgot?`<button class="text-btn" data-action="show-forgot">Password dimenticata?</button>`:''}<div class="auth-switch">${signup?'Hai già un account?':'Non hai ancora un account?'} <button data-action="${signup?'show-login':'show-signup'}">${signup?'Accedi':'Registrati'}</button></div>${forgot?`<button class="text-btn" data-action="show-login">← Torna all'accesso</button>`:''}</section></main>`
}
function resetPasswordView(){return `<main class="auth-shell page-enter"><section class="auth-brand"><div class="auth-chef">${icon('chef')}</div><h1>Nuova password</h1><p>Scegli una nuova password per il tuo profilo.</p></section><section class="auth-card"><label>Nuova password</label><input id="newPassword" type="password" autocomplete="new-password" placeholder="Almeno 6 caratteri"><button class="primary-btn green" data-action="update-password">Salva nuova password</button></section></main>`}
function homeView(){const name=state.settings.displayName?.trim();return `<main class="app-shell page-enter"><div class="home-head"><div class="hello"><div class="hello-mark">${icon('chef')}</div><div><h1>${name?`Ciao, ${esc(name)}!`:'Ciao!'}</h1><p>I tuoi ricettari, sempre con te</p></div></div><button class="circle-btn primary" data-action="new-cookbook">${icon('plus')}</button></div>${state.cookbooks.length?`<section class="book-grid">${state.cookbooks.map(bookCard).join('')}</section>`:`<div class="empty"><span class="emoji">📚</span><h2>Il tuo primo ricettario</h2><p>Crea una raccolta, scegli il colore della copertina e comincia a salvare le tue ricette.</p><button class="primary-btn green" data-action="new-cookbook">Crea ricettario</button></div>`}${bottomNav('home')}</main>`}
function bookCard(b){return `<article class="book-card"><button class="book-cover" style="background:${b.color}" data-open-book="${b.id}"><span class="book-symbol">${bookSymbol(b.name)}</span><h2>${esc(b.name)}</h2><small>${b.recipes.length} ${b.recipes.length===1?'ricetta':'ricette'}</small></button><button class="book-menu" data-edit-book="${b.id}">${icon('edit')}</button></article>`}
function cookbookFormView(){const editing=route.view==='edit-cookbook',b=editing?getCookbook():null,color=b?.color||COLORS[0];return `<main class="app-shell no-nav page-enter"><header class="topbar center"><button class="back-btn" data-action="home">${icon('back')}</button><div class="top-title"><h1>${editing?'Modifica ricettario':'Nuovo ricettario'}</h1></div><span></span></header><div class="preview-wrap"><div class="book-preview"><div class="book-cover" id="bookPreview" style="background:${color}"><span class="book-symbol" id="bookPreviewSymbol">${bookSymbol(b?.name||'')}</span><h2 id="bookPreviewName">${esc(b?.name||'Il mio ricettario')}</h2></div></div></div><section class="panel"><div class="form-group"><label>Nome ricettario <span class="required">*</span></label><input id="bookName" value="${esc(b?.name||'')}" placeholder="Es. Dolci" maxlength="50"></div><div class="form-group"><label>Scegli un colore</label><div class="color-row">${COLORS.map(c=>`<button class="color-dot ${c===color?'selected':''}" style="background:${c}" data-color="${c}"></button>`).join('')}</div></div><div class="button-stack"><button class="primary-btn" data-action="save-cookbook">${editing?'Salva modifiche':'Crea ricettario'}</button>${editing?`<button class="danger-btn" data-action="delete-cookbook">Elimina ricettario</button>`:''}</div></section></main>`}
function cookbookView(){const b=getCookbook();if(!b)return homeView();return `<main class="app-shell no-nav page-enter"><section class="cookbook-hero" style="background:${b.color}"><header class="topbar center"><button class="back-btn" data-action="home">${icon('back')}</button><div class="top-title"><h1>${esc(b.name)}</h1><p>${b.recipes.length} ${b.recipes.length===1?'ricetta':'ricette'}</p></div><button class="circle-btn" data-action="edit-current-book">${icon('edit')}</button></header><div class="hero-search"><input class="search-input" id="recipeSearch" placeholder="Cerca in ${esc(b.name)}..."><button class="filter-btn">${icon('filter')}</button></div><div class="book-actions"><button data-action="book-pdf">${icon('download','inline-icon')} PDF ricettario</button><button data-action="share-book">${icon('share','inline-icon')} Condividi PDF</button></div></section><section class="recipe-list" id="recipeList">${renderRecipeList(b.recipes.map(r=>({book:b,recipe:r})))}</section><button class="fab" data-action="new-recipe">${icon('plus')} Aggiungi ricetta</button></main>`}
function renderRecipeList(entries,emptyMessage='Ancora nessuna ricetta'){if(!entries.length)return `<div class="empty"><span class="emoji">🥣</span><h2>${emptyMessage}</h2><p>Le ricette che salvi compariranno qui.</p></div>`;return entries.map(({book,recipe:r})=>`<article class="recipe-item"><div class="recipe-open" data-open-recipe="${r.id}" data-book-id="${book.id}">${r.photo?`<img class="recipe-thumb" src="${r.photo}" alt="">`:`<div class="recipe-thumb recipe-fallback"><span class="book-symbol">${bookSymbol(book.name)}</span></div>`}<div class="recipe-copy"><h3>${esc(r.name)}</h3><p>${route.view==='search'||route.view==='favorites'?`<span class="recipe-book-label">${esc(book.name)}</span> · `:''}${esc(metaText(r))}</p></div></div><button class="heart-btn ${r.favorite?'active':''}" data-favorite-recipe="${r.id}" data-book-id="${book.id}">${icon('heart')}</button></article>`).join('')}
function beginNewRecipe(){ingredientDraft=[];draftPhoto=null;draftPhotoChanged=false;go('new-recipe',route.cookbookId)}
function beginEditRecipe(){const r=getRecipe();if(!r)return;ingredientDraft=[...r.ingredients];draftPhoto=r.photo||null;draftPhotoChanged=false;go('edit-recipe',route.cookbookId,route.recipeId)}
function recipeFormView(){const editing=route.view==='edit-recipe',r=editing?getRecipe():null,b=getCookbook();if(!b)return homeView();return `<main class="app-shell no-nav page-enter"><header class="topbar center"><button class="back-btn" data-action="${editing?'recipe':'book'}">${icon('back')}</button><div class="top-title"><h1>${editing?'Modifica ricetta':'Nuova ricetta'}</h1></div><button class="top-save" data-action="save-recipe">Salva</button></header><section class="panel"><div class="form-group"><label>Nome della ricetta <span class="required">*</span></label><input id="recipeName" value="${esc(r?.name||'')}" placeholder="Es. Torta di mele" maxlength="100"></div><div class="form-group"><label>Ingredienti <span class="required">*</span></label><div class="ingredient-add"><input id="ingredientInput" placeholder="Es. 300 g farina"><button class="add-btn" data-action="add-ingredient">＋ Aggiungi</button></div><div class="ingredients-editor" id="ingredientList">${ingredientEditorHtml()}</div></div><div class="form-group"><label>Procedimento <span class="optional">(facoltativo)</span></label><textarea id="procedure" placeholder="Scrivi qui il procedimento...">${esc(r?.procedure||'')}</textarea></div><div class="form-group"><label>Foto <span class="optional">(facoltativa)</span></label><div class="photo-zone" id="photoBox">${photoBoxHtml()}</div><div class="photo-buttons"><button data-action="camera-photo">📷 Scatta foto</button><button data-action="gallery-photo">▣ Scegli dalla galleria</button></div></div><div class="form-group"><label>Cottura <span class="optional">(facoltativa)</span></label><div class="cooking-grid"><select id="method"><option value="">Metodo</option>${['Forno statico','Forno ventilato','Padella','Friggitrice ad aria','Pentola','Vapore','Senza cottura','Altro'].map(x=>`<option ${r?.cooking?.method===x?'selected':''}>${x}</option>`).join('')}</select><div class="input-unit"><input id="temperature" type="number" min="0" max="500" value="${esc(r?.cooking?.temperature||'')}" placeholder="180"><span>°C</span></div><div class="input-unit"><input id="time" type="number" min="0" max="9999" value="${esc(r?.cooking?.time||'')}" placeholder="35"><span>min</span></div></div></div><button class="primary-btn green" data-action="save-recipe">${editing?'Salva modifiche':'Salva ricetta'}</button></section></main>`}
function ingredientEditorHtml(){return ingredientDraft.map((x,i)=>`<div class="ingredient-edit"><button class="remove-ing" data-remove-ing="${i}">−</button><input value="${esc(x)}" data-ing-index="${i}"></div>`).join('')}
function photoBoxHtml(){return draftPhoto?`<div class="photo-preview"><img src="${draftPhoto}" alt="Anteprima foto"><button class="remove-photo" data-action="remove-photo">×</button></div>`:`<div class="photo-empty"><div><div class="camera-big">▣</div><strong>Aggiungi una foto</strong><div style="font-size:12px;margin-top:4px">Scattala ora oppure sceglila dalla galleria</div></div></div>`}
function recipeView(){const r=getRecipe(),b=getCookbook();if(!r||!b)return cookbookView();const hasPhoto=!!r.photo;return `<main class="app-shell no-nav recipe-page page-enter">${hasPhoto?`<div class="recipe-photo-wrap"><img src="${r.photo}" alt="${esc(r.name)}"><div class="recipe-overlay"><button class="back-btn" data-action="book">${icon('back')}</button><div class="recipe-overlay-actions"><button class="circle-btn heart-top ${r.favorite?'active':''}" data-action="toggle-current-favorite">${icon('heart')}</button><button class="circle-btn" data-action="share-recipe">${icon('share')}</button></div></div></div>`:`<header class="topbar center"><button class="back-btn" data-action="book">${icon('back')}</button><div class="top-title"><h1>Ricetta</h1></div><button class="circle-btn" data-action="share-recipe">${icon('share')}</button></header>`}<article class="recipe-sheet ${hasPhoto?'':'no-photo'}"><h1 class="recipe-title">${esc(r.name)}</h1><div class="recipe-meta">${r.cooking?.time?`<span class="meta-chip">${icon('clock')} ${r.cooking.time} min</span>`:''}${r.cooking?.method?`<span class="meta-chip">${icon('oven')} ${esc(r.cooking.method)}</span>`:''}${r.cooking?.temperature?`<span class="meta-chip">${icon('temp')} ${r.cooking.temperature} °C</span>`:''}</div><div class="recipe-toolbar"><button data-action="recipe-pdf">${icon('download')}<span>Scarica PDF</span></button><button data-action="share-recipe">${icon('share')}<span>Condividi</span></button><button data-action="edit-recipe">${icon('edit')}<span>Modifica</span></button></div><section class="recipe-section"><h2>Ingredienti</h2><ul class="clean-list">${r.ingredients.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>${r.procedure?`<section class="recipe-section"><h2>Procedimento</h2><div class="procedure">${esc(r.procedure)}</div></section>`:''}${r.cooking&&(r.cooking.method||r.cooking.temperature||r.cooking.time)?`<section class="recipe-section"><h2>Cottura</h2><div class="cooking-card">${r.cooking.method?`<div class="cook-stat"><span>Metodo</span>${esc(r.cooking.method)}</div>`:''}${r.cooking.temperature?`<div class="cook-stat"><span>Temperatura</span>${r.cooking.temperature} °C</div>`:''}${r.cooking.time?`<div class="cook-stat"><span>Tempo</span>${r.cooking.time} min</div>`:''}</div></section>`:''}<div class="button-stack" style="margin-top:26px"><button class="danger-btn" data-action="delete-recipe">Elimina ricetta</button></div></article></main>`}
function searchView(){const entries=allRecipes();return `<main class="app-shell page-enter"><header class="search-header"><h1>Cerca</h1></header><div class="search-wrap" id="globalSearchWrap"><span class="search-ico">${icon('search')}</span><input class="search-input" id="globalSearch" placeholder="Nome o ingrediente" autocomplete="off"><button class="clear-search" data-action="clear-search">×</button></div><div class="segmented"><button class="${searchMode==='all'?'active':''}" data-search-mode="all">Tutte</button><button class="${searchMode==='name'?'active':''}" data-search-mode="name">Ricette</button><button class="${searchMode==='ingredients'?'active':''}" data-search-mode="ingredients">Ingredienti</button></div><div id="searchResults">${searchResultsHtml(entries,'')}</div>${bottomNav('search')}</main>`}
function searchResultsHtml(entries,q){const qq=q.toLowerCase().trim();let filtered=entries;if(qq)filtered=entries.filter(({recipe:r})=>searchMode==='name'?r.name.toLowerCase().includes(qq):searchMode==='ingredients'?r.ingredients.some(i=>i.toLowerCase().includes(qq)):r.name.toLowerCase().includes(qq)||r.ingredients.some(i=>i.toLowerCase().includes(qq)));return `<div class="result-count">${filtered.length} ${filtered.length===1?'risultato':'risultati'}</div><section class="recipe-list">${renderRecipeList(filtered,'Nessuna ricetta trovata')}</section>`}
function favoritesView(){const fav=allRecipes().filter(x=>x.recipe.favorite);return `<main class="app-shell page-enter"><header class="search-header"><h1>Preferiti</h1></header>${fav.length?`<section class="recipe-list">${renderRecipeList(fav)}</section>`:`<div class="empty"><span class="emoji">♡</span><h2>Nessun preferito</h2><p>Tocca il cuore su una ricetta per ritrovarla rapidamente qui.</p></div>`}${bottomNav('favorites')}</main>`}
function settingsView(){const n=state.settings.displayName?.trim()||currentUser?.email?.split('@')[0]||'La mia cucina';const localCount=deviceLocalState.cookbooks?.reduce((a,b)=>a+b.recipes.length,0)||0;const migrated=localStorage.getItem(`ricettario-migrated:${currentUser?.id}`)==='1';return `<main class="app-shell page-enter"><header class="settings-header"><h1>Impostazioni</h1></header><section class="settings-section"><h2>Il mio account</h2><div class="settings-card"><div class="setting-row"><div class="setting-icon">${icon('user')}</div><div><strong>Nome utente</strong><small>${esc(currentUser?.email||'')}</small></div><button data-action="edit-display-name">${esc(n)} ›</button></div><div class="setting-row"><div class="setting-icon">${icon('cloud')}</div><div><strong>Sincronizzazione</strong><small>Attiva su tutti i dispositivi</small></div><small>Online ✓</small></div><div class="setting-row"><div class="setting-icon">${icon('backup')}</div><div><strong>Backup dati</strong></div><div class="setting-actions"><button data-action="export-backup">Esporta</button><button data-action="import-backup">Importa</button></div></div>${localCount&&!migrated?`<div class="setting-row migration-row"><div class="setting-icon">${icon('restore')}</div><div><strong>Ricette del vecchio dispositivo</strong><small>${localCount} ricette locali trovate</small></div><button data-action="migrate-local">Trasferisci</button></div>`:''}</div></section><section class="settings-section"><h2>Altro</h2><div class="settings-card"><div class="setting-row"><div class="setting-icon">＋</div><div><strong>Installa l'app</strong></div><button data-action="install-app">Apri ›</button></div><div class="setting-row"><div class="setting-icon">${icon('info')}</div><div><strong>Informazioni</strong></div><small>v${APP_VERSION}</small></div><div class="setting-row"><div class="setting-icon">${icon('logout')}</div><div><strong>Esci dal profilo</strong></div><button data-action="logout">Logout</button></div></div><p class="settings-note">Ricettari, ricette e foto sono salvati nel tuo profilo online e sincronizzati fra i dispositivi. Una copia di cache resta sul dispositivo per la consultazione.</p></section><section class="settings-section"><button class="danger-btn" data-action="reset-cloud">Cancella tutti i miei ricettari</button></section>${bottomNav('settings')}</main>`}

function render(){const app=document.querySelector('#app');if(!currentUser){app.innerHTML=recoveryMode?resetPasswordView():authView(route.view==='signup'?'signup':route.view==='forgot'?'forgot':'login',route.message||'');bindEvents();return}let html='';if(route.view==='home')html=homeView();else if(route.view==='new-cookbook'||route.view==='edit-cookbook')html=cookbookFormView();else if(route.view==='cookbook')html=cookbookView();else if(route.view==='new-recipe'||route.view==='edit-recipe')html=recipeFormView();else if(route.view==='recipe')html=recipeView();else if(route.view==='search')html=searchView();else if(route.view==='favorites')html=favoritesView();else if(route.view==='settings')html=settingsView();else html=homeView();app.innerHTML=html;bindEvents()}
function bindEvents(){document.querySelectorAll('[data-action]').forEach(el=>el.addEventListener('click',handleAction));document.querySelectorAll('[data-nav]').forEach(el=>el.addEventListener('click',()=>go(el.dataset.nav)));document.querySelectorAll('[data-open-book]').forEach(el=>el.addEventListener('click',()=>go('cookbook',el.dataset.openBook)));document.querySelectorAll('[data-edit-book]').forEach(el=>el.addEventListener('click',e=>{e.stopPropagation();go('edit-cookbook',el.dataset.editBook)}));bindDynamicRecipeEvents();document.querySelectorAll('[data-color]').forEach(el=>el.addEventListener('click',()=>selectColor(el)));document.querySelectorAll('[data-search-mode]').forEach(el=>el.addEventListener('click',()=>{searchMode=el.dataset.searchMode;render();setTimeout(()=>document.querySelector('#globalSearch')?.focus(),20)}));document.querySelectorAll('[data-remove-ing]').forEach(btn=>btn.addEventListener('click',()=>{syncIngredientDraft();ingredientDraft.splice(+btn.dataset.removeIng,1);refreshIngredientEditor()}));document.querySelectorAll('[data-ing-index]').forEach(inp=>inp.addEventListener('input',syncIngredientDraft));const bookName=document.querySelector('#bookName');if(bookName)bookName.addEventListener('input',()=>{const n=bookName.value.trim()||'Il mio ricettario';document.querySelector('#bookPreviewName').textContent=n;document.querySelector('#bookPreviewSymbol').innerHTML=bookSymbol(n)});const recipeSearch=document.querySelector('#recipeSearch');if(recipeSearch)recipeSearch.addEventListener('input',()=>{const b=getCookbook(),q=recipeSearch.value.toLowerCase().trim(),entries=b.recipes.filter(r=>r.name.toLowerCase().includes(q)||r.ingredients.some(i=>i.toLowerCase().includes(q))).map(r=>({book:b,recipe:r}));document.querySelector('#recipeList').innerHTML=renderRecipeList(entries,'Nessuna ricetta trovata');bindDynamicRecipeEvents()});const globalSearch=document.querySelector('#globalSearch');if(globalSearch)globalSearch.addEventListener('input',()=>{document.querySelector('#globalSearchWrap').classList.toggle('has-value',!!globalSearch.value);document.querySelector('#searchResults').innerHTML=searchResultsHtml(allRecipes(),globalSearch.value);bindDynamicRecipeEvents()});document.querySelector('#photoInput').onchange=handlePhotoInput;document.querySelector('#cameraInput').onchange=handlePhotoInput;document.querySelector('#backupInput').onchange=handleBackupImport}
function bindDynamicRecipeEvents(){document.querySelectorAll('[data-open-recipe]').forEach(el=>el.addEventListener('click',()=>go('recipe',el.dataset.bookId,el.dataset.openRecipe)));document.querySelectorAll('[data-favorite-recipe]').forEach(el=>el.addEventListener('click',async e=>{e.stopPropagation();await toggleFavorite(el.dataset.bookId,el.dataset.favoriteRecipe);render()}))}
function selectColor(el){document.querySelectorAll('[data-color]').forEach(x=>x.classList.remove('selected'));el.classList.add('selected');document.querySelector('#bookPreview')?.style.setProperty('background',el.dataset.color)}

async function handleAction(e){if(loading)return;const a=e.currentTarget.dataset.action;
  if(a==='show-signup'){route={view:'signup'};return render()}if(a==='show-login'){route={view:'auth'};return render()}if(a==='show-forgot'){route={view:'forgot'};return render()}if(a==='signup')return signUp();if(a==='login')return signIn();if(a==='send-reset')return sendPasswordReset();if(a==='update-password')return updatePassword();if(a==='logout')return signOut();
  if(a==='home')return go('home');if(a==='book')return go('cookbook',route.cookbookId);if(a==='recipe')return go('recipe',route.cookbookId,route.recipeId);if(a==='new-cookbook')return go('new-cookbook');if(a==='edit-current-book')return go('edit-cookbook',route.cookbookId);if(a==='save-cookbook')return saveCookbook();if(a==='delete-cookbook')return deleteCookbook();
  if(a==='new-recipe')return beginNewRecipe();if(a==='edit-recipe')return beginEditRecipe();if(a==='add-ingredient')return addIngredient();if(a==='save-recipe')return saveRecipe();if(a==='delete-recipe')return deleteRecipe();if(a==='gallery-photo')return document.querySelector('#photoInput').click();if(a==='camera-photo')return document.querySelector('#cameraInput').click();if(a==='remove-photo'){draftPhoto=null;draftPhotoChanged=true;return refreshPhotoBox()}
  if(a==='recipe-pdf')return downloadRecipePdf(getRecipe());if(a==='share-recipe')return shareRecipePdf(getRecipe());if(a==='book-pdf')return downloadCookbookPdf(getCookbook());if(a==='share-book')return shareCookbookPdf(getCookbook());if(a==='toggle-current-favorite'){await toggleFavorite(route.cookbookId,route.recipeId);return render()}
  if(a==='clear-search'){const i=document.querySelector('#globalSearch');if(i){i.value='';document.querySelector('#globalSearchWrap').classList.remove('has-value');document.querySelector('#searchResults').innerHTML=searchResultsHtml(allRecipes(),'');bindDynamicRecipeEvents();i.focus()}return}
  if(a==='edit-display-name')return editDisplayName();if(a==='export-backup')return exportBackup();if(a==='import-backup')return document.querySelector('#backupInput').click();if(a==='migrate-local')return migrateLocalData();if(a==='reset-cloud')return resetCloud();if(a==='install-app')return installApp();
}

async function signUp(){const name=document.querySelector('#authName')?.value.trim(),email=document.querySelector('#authEmail')?.value.trim(),password=document.querySelector('#authPassword')?.value||'';if(!name||!email||password.length<6)return showToast('Inserisci nome, email e una password di almeno 6 caratteri');setBusy(true,'Creo il profilo...');const {data,error}=await sb.auth.signUp({email,password,options:{data:{display_name:name},emailRedirectTo:APP_URL}});setBusy(false);if(error)return alert(error.message);if(data.session){currentUser=data.user;await loadCloudState();go('home')}else{route={view:'auth',message:'Registrazione completata. Controlla la tua email e conferma il profilo, poi accedi.'};render()}}
async function signIn(){const email=document.querySelector('#authEmail')?.value.trim(),password=document.querySelector('#authPassword')?.value||'';if(!email||!password)return showToast('Inserisci email e password');setBusy(true,'Accesso...');const {data,error}=await sb.auth.signInWithPassword({email,password});if(error){setBusy(false);return alert(error.message)}currentUser=data.user;await loadCloudState();setBusy(false);go('home')}
async function signOut(){setBusy(true,'Esco dal profilo...');await sb.auth.signOut();currentUser=null;state=clone(DEFAULT_STATE);route={view:'auth'};setBusy(false);render()}
async function sendPasswordReset(){const email=document.querySelector('#authEmail')?.value.trim();if(!email)return showToast('Inserisci la tua email');setBusy(true,'Invio email...');const {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:APP_URL});setBusy(false);if(error)return alert(error.message);route={view:'auth',message:'Ti abbiamo inviato un link per impostare una nuova password.'};render()}
async function updatePassword(){const password=document.querySelector('#newPassword')?.value||'';if(password.length<6)return showToast('La password deve avere almeno 6 caratteri');setBusy(true,'Salvo la nuova password...');const {error}=await sb.auth.updateUser({password});setBusy(false);if(error)return alert(error.message);recoveryMode=false;showToast('Password aggiornata');go('home')}

async function loadCloudState(){if(!currentUser)return;try{const [profileRes,booksRes,recipesRes]=await Promise.all([sb.from('profiles').select('display_name').eq('id',currentUser.id).maybeSingle(),sb.from('cookbooks').select('*').order('sort_order').order('created_at'),sb.from('recipes').select('*').order('sort_order').order('created_at',{ascending:false})]);if(profileRes.error)throw profileRes.error;if(booksRes.error)throw booksRes.error;if(recipesRes.error)throw recipesRes.error;const books=(booksRes.data||[]).map(b=>({id:b.id,name:b.name,color:b.color||COLORS[0],createdAt:b.created_at,recipes:[]}));const map=new Map(books.map(b=>[b.id,b]));for(const row of recipesRes.data||[]){const b=map.get(row.cookbook_id);if(!b)continue;let photo=null;if(row.photo_path){const {data}=await sb.storage.from('recipe-photos').createSignedUrl(row.photo_path,60*60*24*7);photo=data?.signedUrl||null}b.recipes.push({id:row.id,name:row.title,ingredients:Array.isArray(row.ingredients)?row.ingredients:[],procedure:row.procedure||'',photo,photoPath:row.photo_path||null,cooking:{method:row.cooking_method||'',temperature:row.cooking_temperature??'',time:row.cooking_time??''},favorite:!!row.favorite,createdAt:row.created_at,updatedAt:row.updated_at})}state={version:4,cookbooks:books,settings:{displayName:profileRes.data?.display_name||currentUser.user_metadata?.display_name||currentUser.email?.split('@')[0]||'',theme:'light'}};await cacheCloud()}catch(err){console.error(err);const cached=await cloudCache();if(cached){state=cached;showToast('Sei offline: mostro l’ultima copia salvata')}else{state=clone(DEFAULT_STATE);alert('Non riesco a caricare i tuoi ricettari. Controlla la connessione e riprova.')}}}
async function uploadPhoto(recipeId,dataUrl){if(!dataUrl?.startsWith('data:'))return null;const res=await fetch(dataUrl),blob=await res.blob(),path=`${currentUser.id}/${recipeId}/${Date.now()}.jpg`;const {error}=await sb.storage.from('recipe-photos').upload(path,blob,{contentType:'image/jpeg',upsert:false});if(error)throw error;return path}
async function signedPhoto(path){if(!path)return null;const {data}=await sb.storage.from('recipe-photos').createSignedUrl(path,60*60*24*7);return data?.signedUrl||null}
async function removePhoto(path){if(path)await sb.storage.from('recipe-photos').remove([path])}

async function saveCookbook(){const input=document.querySelector('#bookName'),name=input.value.trim();if(!name){input.focus();return showToast('Inserisci il nome del ricettario')}const color=document.querySelector('.color-dot.selected')?.dataset.color||COLORS[0];setBusy(true,'Salvo il ricettario...');if(route.view==='edit-cookbook'){const b=getCookbook();const {error}=await sb.from('cookbooks').update({name,color}).eq('id',b.id).eq('user_id',currentUser.id);if(error){setBusy(false);return alert(error.message)}b.name=name;b.color=color}else{const id=uid();const {error}=await sb.from('cookbooks').insert({id,user_id:currentUser.id,name,color,sort_order:state.cookbooks.length});if(error){setBusy(false);return alert(error.message)}state.cookbooks.push({id,name,color,createdAt:new Date().toISOString(),recipes:[]})}await cacheCloud();setBusy(false);showToast('Ricettario salvato');go('home')}
async function deleteCookbook(){const b=getCookbook();if(!b||!confirm(`Eliminare il ricettario “${b.name}” e tutte le sue ricette?`))return;setBusy(true,'Elimino il ricettario...');const paths=b.recipes.map(r=>r.photoPath).filter(Boolean);if(paths.length)await sb.storage.from('recipe-photos').remove(paths);const {error}=await sb.from('cookbooks').delete().eq('id',b.id).eq('user_id',currentUser.id);if(error){setBusy(false);return alert(error.message)}state.cookbooks=state.cookbooks.filter(x=>x.id!==b.id);await cacheCloud();setBusy(false);showToast('Ricettario eliminato');go('home')}
function addIngredient(){const input=document.querySelector('#ingredientInput'),v=input?.value.trim();if(!v)return;syncIngredientDraft();ingredientDraft.push(v);input.value='';refreshIngredientEditor();input.focus()}
function syncIngredientDraft(){document.querySelectorAll('[data-ing-index]').forEach(inp=>ingredientDraft[+inp.dataset.ingIndex]=inp.value.trim())}
function refreshIngredientEditor(){const el=document.querySelector('#ingredientList');if(!el)return;el.innerHTML=ingredientEditorHtml();el.querySelectorAll('[data-remove-ing]').forEach(btn=>btn.addEventListener('click',()=>{syncIngredientDraft();ingredientDraft.splice(+btn.dataset.removeIng,1);refreshIngredientEditor()}));el.querySelectorAll('[data-ing-index]').forEach(inp=>inp.addEventListener('input',syncIngredientDraft))}
function refreshPhotoBox(){const box=document.querySelector('#photoBox');if(box)box.innerHTML=photoBoxHtml();box?.querySelector('[data-action="remove-photo"]')?.addEventListener('click',()=>{draftPhoto=null;draftPhotoChanged=true;refreshPhotoBox()})}
async function handlePhotoInput(e){const file=e.target.files?.[0];if(!file)return;try{draftPhoto=await resizeImageFile(file);draftPhotoChanged=true;refreshPhotoBox();showToast('Foto aggiunta')}catch{showToast('Impossibile leggere la foto')}e.target.value=''}
function resizeImageFile(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const max=1500;let w=img.width,h=img.height;if(w>max||h>max){const s=Math.min(max/w,max/h);w=Math.round(w*s);h=Math.round(h*s)}const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);resolve(c.toDataURL('image/jpeg',.82))};img.src=reader.result};reader.readAsDataURL(file)})}
async function saveRecipe(){syncIngredientDraft();const pending=document.querySelector('#ingredientInput')?.value.trim();if(pending)ingredientDraft.push(pending);ingredientDraft=ingredientDraft.map(x=>x.trim()).filter(Boolean);const nameInput=document.querySelector('#recipeName'),name=nameInput.value.trim();if(!name){nameInput.focus();return showToast('Inserisci il nome della ricetta')}if(!ingredientDraft.length)return showToast('Inserisci almeno un ingrediente');const b=getCookbook(),editing=route.view==='edit-recipe',existing=editing?getRecipe():null,id=existing?.id||uid();setBusy(true,'Salvo la ricetta...');try{let photoPath=existing?.photoPath||null;if(draftPhotoChanged){if(draftPhoto?.startsWith('data:')){const newPath=await uploadPhoto(id,draftPhoto);if(photoPath)await removePhoto(photoPath);photoPath=newPath}else if(!draftPhoto&&photoPath){await removePhoto(photoPath);photoPath=null}}const row={id,user_id:currentUser.id,cookbook_id:b.id,title:name,ingredients:[...ingredientDraft],procedure:document.querySelector('#procedure').value.trim()||null,cooking_method:document.querySelector('#method').value||null,cooking_temperature:document.querySelector('#temperature').value?+document.querySelector('#temperature').value:null,cooking_time:document.querySelector('#time').value?+document.querySelector('#time').value:null,photo_path:photoPath,favorite:existing?.favorite||false,sort_order:0};const {error}=editing?await sb.from('recipes').update(row).eq('id',id).eq('user_id',currentUser.id):await sb.from('recipes').insert(row);if(error)throw error;const photo=photoPath?await signedPhoto(photoPath):null;const data={id,name,ingredients:[...ingredientDraft],procedure:row.procedure||'',photo,photoPath,cooking:{method:row.cooking_method||'',temperature:row.cooking_temperature??'',time:row.cooking_time??''},favorite:row.favorite,createdAt:existing?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(editing)Object.assign(existing,data);else b.recipes.unshift(data);await cacheCloud();ingredientDraft=[];draftPhoto=null;draftPhotoChanged=false;setBusy(false);showToast('Ricetta salvata');go('recipe',b.id,id)}catch(err){setBusy(false);alert(err.message||'Errore durante il salvataggio')}}
async function deleteRecipe(){const b=getCookbook(),r=getRecipe();if(!b||!r||!confirm(`Eliminare “${r.name}”?`))return;setBusy(true,'Elimino la ricetta...');if(r.photoPath)await removePhoto(r.photoPath);const {error}=await sb.from('recipes').delete().eq('id',r.id).eq('user_id',currentUser.id);if(error){setBusy(false);return alert(error.message)}b.recipes=b.recipes.filter(x=>x.id!==r.id);await cacheCloud();setBusy(false);showToast('Ricetta eliminata');go('cookbook',b.id)}
async function toggleFavorite(bookId,recipeId){const r=getRecipe(bookId,recipeId);if(!r)return;const value=!r.favorite;const {error}=await sb.from('recipes').update({favorite:value}).eq('id',recipeId).eq('user_id',currentUser.id);if(error)return showToast('Errore di sincronizzazione');r.favorite=value;await cacheCloud();showToast(value?'Aggiunta ai preferiti':'Rimossa dai preferiti')}
async function editDisplayName(){const value=prompt('Come vuoi essere chiamata nella Home?',state.settings.displayName||'');if(value===null)return;const name=value.trim().slice(0,40);const {error}=await sb.from('profiles').update({display_name:name}).eq('id',currentUser.id);if(error)return alert(error.message);state.settings.displayName=name;await cacheCloud();render();showToast('Nome aggiornato')}

function pdfRecipeMarkup(r,b,photo){const meta=[];if(r.cooking?.time)meta.push(`<span>◷ ${r.cooking.time} min</span>`);if(r.cooking?.method)meta.push(`<span>▣ ${esc(r.cooking.method)}</span>`);if(r.cooking?.temperature)meta.push(`<span>♨ ${r.cooking.temperature} °C</span>`);return `<article class="pdf-recipe">${photo?`<img class="pdf-hero" src="${photo}" alt="">`:''}<div class="pdf-sheet ${photo?'with-photo':''}"><h1>${esc(r.name)}</h1>${meta.length?`<div class="pdf-meta">${meta.join('')}</div>`:''}<section><h2>Ingredienti</h2><ul>${r.ingredients.map(i=>`<li>${esc(i)}</li>`).join('')}</ul></section>${r.procedure?`<section><h2>Procedimento</h2><div class="pdf-procedure">${esc(r.procedure)}</div></section>`:''}${r.cooking&&(r.cooking.method||r.cooking.temperature||r.cooking.time)?`<section><h2>Cottura</h2><div class="pdf-cooking">${r.cooking.method?`<div><small>Metodo</small><strong>${esc(r.cooking.method)}</strong></div>`:''}${r.cooking.temperature?`<div><small>Temperatura</small><strong>${r.cooking.temperature} °C</strong></div>`:''}${r.cooking.time?`<div><small>Tempo</small><strong>${r.cooking.time} min</strong></div>`:''}</div></section>`:''}<footer>${esc(b.name)} · I miei ricettari</footer></div></article>`}
async function photoDataForPdf(src){if(!src)return null;if(src.startsWith('data:'))return src;try{const res=await fetch(src);const blob=await res.blob();return await new Promise((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>resolve(fr.result);fr.onerror=reject;fr.readAsDataURL(blob)})}catch{return src}}
async function canvasForRecipe(r,b){const stage=document.querySelector('#pdfStage');const photo=await photoDataForPdf(r.photo);stage.innerHTML=pdfRecipeMarkup(r,b,photo);const el=stage.firstElementChild;await new Promise(r=>setTimeout(r,80));return await html2canvas(el,{scale:2,useCORS:true,backgroundColor:'#fffaf6',logging:false})}
function addCanvasToPdf(doc,canvas,first=true){const pagePx=canvas.width*297/210;let offset=0,page=0;while(offset<canvas.height){const h=Math.min(pagePx,canvas.height-offset),slice=document.createElement('canvas');slice.width=canvas.width;slice.height=h;slice.getContext('2d').drawImage(canvas,0,offset,canvas.width,h,0,0,canvas.width,h);if(!first||page>0)doc.addPage();const hmm=h*210/canvas.width;doc.addImage(slice.toDataURL('image/jpeg',.94),'JPEG',0,0,210,hmm,undefined,'FAST');offset+=h;page++}return false}
async function buildRecipePdf(r,asBlob=false){if(!window.jspdf?.jsPDF||!window.html2canvas){showToast('Modulo PDF non disponibile');return null}setBusy(true,'Creo il PDF...');try{const {jsPDF}=window.jspdf,doc=new jsPDF({unit:'mm',format:'a4',orientation:'portrait'}),b=getCookbook(),canvas=await canvasForRecipe(r,b);addCanvasToPdf(doc,canvas,true);setBusy(false);return asBlob?doc.output('blob'):doc}catch(err){setBusy(false);console.error(err);alert('Non riesco a creare il PDF. Riprova con Internet attivo.');return null}}
async function buildCookbookPdf(b,asBlob=false){if(!b?.recipes.length)return showToast('Questo ricettario è vuoto'),null;if(!window.jspdf?.jsPDF||!window.html2canvas)return showToast('Modulo PDF non disponibile'),null;setBusy(true,'Creo il ricettario PDF...');try{const {jsPDF}=window.jspdf,doc=new jsPDF({unit:'mm',format:'a4'}),rgb=b.color.replace('#','').match(/.{2}/g).map(x=>parseInt(x,16));doc.setFillColor(...rgb);doc.rect(0,0,210,297,'F');doc.setTextColor(45,38,34);doc.setFont('times','bold');doc.setFontSize(30);doc.text(b.name,105,130,{align:'center'});doc.setFont('helvetica','normal');doc.setFontSize(12);doc.text(`${b.recipes.length} ${b.recipes.length===1?'ricetta':'ricette'}`,105,145,{align:'center'});for(const r of b.recipes){doc.addPage();const canvas=await canvasForRecipe(r,b);let pagePx=canvas.width*297/210,offset=0,firstSlice=true;while(offset<canvas.height){const h=Math.min(pagePx,canvas.height-offset),slice=document.createElement('canvas');slice.width=canvas.width;slice.height=h;slice.getContext('2d').drawImage(canvas,0,offset,canvas.width,h,0,0,canvas.width,h);if(!firstSlice)doc.addPage();doc.addImage(slice.toDataURL('image/jpeg',.94),'JPEG',0,0,210,h*210/canvas.width,undefined,'FAST');offset+=h;firstSlice=false}}setBusy(false);return asBlob?doc.output('blob'):doc}catch(err){setBusy(false);console.error(err);alert('Non riesco a creare il PDF del ricettario.');return null}}
async function downloadRecipePdf(r){const doc=await buildRecipePdf(r);if(doc)doc.save(`${safeFileName(r.name)}.pdf`)}
async function downloadCookbookPdf(b){const doc=await buildCookbookPdf(b);if(doc)doc.save(`${safeFileName(b.name)}-ricettario.pdf`)}
async function sharePdfBlob(blob,fileName,title,text,fallback){const file=new File([blob],fileName,{type:'application/pdf'});if(navigator.canShare&&navigator.canShare({files:[file]})){try{return await navigator.share({title,text,files:[file]})}catch(e){if(e.name==='AbortError')return}}showToast('Condivisione file non supportata: scarico il PDF');fallback()}
async function shareRecipePdf(r){const blob=await buildRecipePdf(r,true);if(blob)await sharePdfBlob(blob,`${safeFileName(r.name)}.pdf`,r.name,`Ricetta: ${r.name}`,()=>downloadRecipePdf(r))}
async function shareCookbookPdf(b){const blob=await buildCookbookPdf(b,true);if(blob)await sharePdfBlob(blob,`${safeFileName(b.name)}-ricettario.pdf`,b.name,`Ricettario: ${b.name}`,()=>downloadCookbookPdf(b))}

function exportBackup(){const payload=JSON.stringify({...state,accountEmail:currentUser?.email,exportedAt:new Date().toISOString()},null,2),blob=new Blob([payload],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`ricettari-backup-${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000);showToast('Backup esportato')}
async function handleBackupImport(e){const file=e.target.files?.[0];if(!file)return;try{const raw=normalizeState(JSON.parse(await file.text()));if(!raw.cookbooks.length)throw new Error();if(!confirm('Importare questo backup nel tuo profilo? Le ricette esistenti resteranno e il backup verrà aggiunto.'))return;await importStateToCloud(raw);await loadCloudState();showToast('Backup importato');go('home')}catch{alert('Il file selezionato non è un backup valido.')}finally{e.target.value=''}}
async function importStateToCloud(source){for(const b of source.cookbooks){const bid=uid();let {error}=await sb.from('cookbooks').insert({id:bid,user_id:currentUser.id,name:b.name,color:b.color||COLORS[0],sort_order:state.cookbooks.length});if(error)throw error;for(const r of b.recipes){const rid=uid();let path=null;if(r.photo?.startsWith('data:'))path=await uploadPhoto(rid,r.photo);const row={id:rid,user_id:currentUser.id,cookbook_id:bid,title:r.name,ingredients:r.ingredients||[],procedure:r.procedure||null,cooking_method:r.cooking?.method||null,cooking_temperature:r.cooking?.temperature?+r.cooking.temperature:null,cooking_time:r.cooking?.time?+r.cooking.time:null,photo_path:path,favorite:!!r.favorite};({error}=await sb.from('recipes').insert(row));if(error)throw error}}}
async function migrateLocalData(){if(!deviceLocalState.cookbooks.length)return showToast('Non ci sono ricette locali da trasferire');if(!confirm('Trasferire nel tuo profilo online i ricettari salvati in precedenza su questo dispositivo?'))return;setBusy(true,'Trasferisco le ricette...');try{await importStateToCloud(deviceLocalState);localStorage.setItem(`ricettario-migrated:${currentUser.id}`,'1');await loadCloudState();setBusy(false);showToast('Ricette trasferite');go('home')}catch(err){setBusy(false);alert(err.message||'Trasferimento non riuscito')}}
async function resetCloud(){if(!confirm('Vuoi cancellare tutti i ricettari del tuo profilo?'))return;if(!confirm('Conferma definitiva: questa operazione non può essere annullata senza un backup.'))return;setBusy(true,'Cancello i dati...');const paths=allRecipes().map(x=>x.recipe.photoPath).filter(Boolean);if(paths.length)await sb.storage.from('recipe-photos').remove(paths);const {error}=await sb.from('cookbooks').delete().eq('user_id',currentUser.id);setBusy(false);if(error)return alert(error.message);state.cookbooks=[];await cacheCloud();showToast('Dati cancellati');go('home')}
async function installApp(){if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null}else alert('Apri il menu del browser e scegli “Installa app” o “Aggiungi a schermata Home”.')}

window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(console.warn));
async function init(){deviceLocalState=await loadDeviceLocal();if(!window.supabase){route={view:'auth',message:'Connessione al servizio account non disponibile. Ricarica con Internet attivo.'};return render()}sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});sb.auth.onAuthStateChange(async(event,session)=>{if(event==='PASSWORD_RECOVERY'){currentUser=session?.user||null;recoveryMode=true;render();return}if(event==='SIGNED_OUT'){currentUser=null;state=clone(DEFAULT_STATE);route={view:'auth'};render()}});const {data}=await sb.auth.getSession();currentUser=data.session?.user||null;if(currentUser){setBusy(true,'Carico i tuoi ricettari...');await loadCloudState();setBusy(false);route={view:'home'}}else route={view:'auth'};render()}
init();
